### ISSUE TITLE
Unexpected border shown on Table components on mobile

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#787]
**Describe the bug**

Unexpected border is shown on Table components on mobile, despite `bordered` prop not set.

**To Reproduce**

Look at [default Table example](https://gel.westpacgroup.com.au/design-system/components/tables?b=WBC&tab=code).

**Expected behavior**

Table on mobile to look like on 466px wide screens and larger.

**Screenshots**

466px wide screens and larger:

![image](https://user-images.githubusercontent.com/5426427/129210848-93f89bbd-740e-40d8-a053-9307d122e6ed.png)

465px wide screens and smaller:

![image](https://user-images.githubusercontent.com/5426427/129210906-daee32bf-ab57-4049-bbeb-780ad52a70bb.png)

**Comment by jonnystening** [comment]
This was intentional, a styling treatment to indicate the horizontal scrolling clipping edge for wide tables in narrow viewpoints. Originally came from v3 of Bootstrap https://getbootstrap.com/docs/3.4/css/#tables-responsive

We're going to be removing this border as it's no longer required 👍

https://github.com/WestpacGEL/GEL/pull/805
