### ISSUE TITLE
`@westpac/tabcordion` doesn't provide `react-dom`, requested by `react-use-measure`

### ISSUE THREAD

**Issue by wojtekmaj** [WestpacGEL/GEL#807]
**Describe the bug**

Installing @westpac/tabcordion with Yarn produces the following warning:

```
@westpac/tabcordion@npm:2.1.2 doesn't provide `react-dom`, requested by `react-use-measure`

Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

when running the command for details, Yarn returns:

```
@westpac/tabcordion@npm:2.1.2 [22957] doesn't provide react-dom, breaking the following requirements:

react-use-measure@npm:2.0.4 [6b0e2] → >=16.13 ✘
```

**To Reproduce**

`yarn add @westpac/tabcordion` using Yarn >=2

**Expected behavior**

No warning

**Additional context**

To fix this, simply add `react-dom` as `@westpac/tabcordion`'s peerDependency.

This can be worked around in Yarn by using `packageExtensions`:

```
packageExtensions:
  "@westpac/tabcordion@*":
    peerDependencies:
      react-dom: ">=16.13.0"
```

**Comment by dominikwilkowski** [comment]
Oh yeah I don't think we will be able to support yarn v2.
I just checked the peer dependencies and they are all correct on our end.
`react-use-measure` does have it's peer dependencies stuck in react 16 land which is why is "error" is occurring. https://github.com/pmndrs/react-use-measure/blob/master/package.json#L50

So for GEL we only use yarn v1 and won't support the [non-standard way](https://next.yarnpkg.com/features/pnp) it installs dependencies. We might make this clear in the docs and in the dependencies making yarn v1 a dep.

**Comment by wojtekmaj** [comment]
Well it does install on Yarn 2 just fine, it's just a warning, not error. I don't think it's so critical to just drop Yard support. Especially since I'm already using it with Yarn 3 😅

**Comment by dominikwilkowski** [comment]
Oh sorry to make that a bit more clear from my end: We won't put any work into making it work for yarn >1 but we will also not do any work in making it NOT work. So if it does, more power to you :)
There isn't anything we can do here since we don't control the peer dependencies of `react-use-measure`. But they are not enforced either that's why they are peer dependencies. So this should not be an issue right?
You might want to open an issue in the `react-use-measure` repo and ask them to widen the peer dep range to include 17 since 17 is backwards compatible and seems to work fine with `react-use-measure`.

**Comment by wojtekmaj** [comment]
>=16.13 DOES include 17. The issue is that react-dom peerDependency is missing from @westpac/tabcordion.

https://github.com/WestpacGEL/GEL/blob/7de496eaa3774e6b0336e3b326ff3a74de2e2d23/components/tabcordion/package.json#L66-L69

**Comment by dominikwilkowski** [comment]
I got you. Mhhh 🤔 ... we could add it but would have to add it in all components that have dependencies that require `react-dom` or should we just do it everywhere? Things to ponder I guess

**Comment by wojtekmaj** [comment]
From what I see, GEL is heavily dependent on `react-dom` anyway; there's no way of using it in non-browser environments, at least not now.

Should you ever plan to expand GEL to React Native for example, moving react-dom to `optionalDependencies` would make sense, but that's an entirely different story.
